spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: create
auth:
  jwt:
    issuer: moomoo
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 24
    refreshTokenExpirationHour: 168